[package]
name = "fick"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"]}
regex = "1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
file_reader = { path = "../../toolbox/file_reader" }
dlog = { path = "../../toolbox//dlog" }
once_cell = "1.19"
crossterm = "0.29.0"
ratatui = "0.29.0"

