[[filters]]
category = "paycheck"
patterns = [
    "Internet Banking E-TRANSFER (\\d+) RAMARK PARK MODELS LTD."
]
filter_on_match = true

[[filters]] 
category = "etransfer"
patterns = [
    "Internet Banking E-Transfer"
]
filter_on_match = true

[[filters]]
category = "returns"
patterns = [
    "mdse return"
]
filter_on_match = true

[[filters]] 
category = "instore"
patterns = [
    "point of sale"
]
filter_on_match = true

[[filters]]
category = "government"
patterns = [
    "Electronic Funds Transfer DEPOSIT"
]
filter_on_match = true

[[filters]]
category = "bank fees"
patterns = [
    "Branch transaction"
]
filter_on_match = true

[[filters]]
category = "aetolia"
patterns = [
    "IRON REALMS"
]
filter_on_match = true

[[filters]]
category = "online"
patterns = [
    "Visa Debit"
]
filter_on_match = true

[[filters]]
category = "weed"
patterns = [
    "Earth to Embers"
]
filter_on_match = true

[[filters]]
category = "groceries"
patterns = [
    "BOYLE GROCERY"
]
filter_on_match = true

[[filters]]
category = "bills"
patterns = [
    "MCSNET",
    "KUBRA/EPCOR",
    "EPCOR",
    "APEXUTIL",
    "Internet Banking E-TRANSFER (\\d+) Bruce Clark"
]
filter_on_match = true

[[filters]]
category = "extras"
patterns = [
    "Internet Banking INTERNET TRANSFER (\\d+)"
]
filter_on_match = true
[[filters]]
category = "gas stations"
patterns = [
    "HOOTER'S TEMPO",
    "BOYLE GAS BAR",
    "BOYLE PAY",
    "PETRO-CANADA 39",
    "GOLD HAPPYS"
]
filter_on_match = true

[[filters]]
category = "subs"
patterns = [
    "Amazon Channels",
    "AMAZON",
    "DISNEY PLUS",
    "NETFLIX.COM",
    "MICROSOFT*TRIAL",
    "Spotify",
    "Audible"
]
filter_on_match = true
